### ISSUE TITLE
Finish html report

### ISSUE THREAD

**Issue by thradec** [EmbedITCZ/dbadvisor#3]

**Comment by t0mz06** [comment]
Hi guys, will start to work on this one

anything in particular you'd like to be implemented? 

I'll have a look to latest bootstrap classes, to see if anything nice could be implemented, also will have a general look if anything can be improved.

Thanks,
Thomas.

**Comment by thradec** [comment]
personally I would start with
- return to usage of online version of jquery and bootstrap, I think the generated file should be self contained, from my PoV the dependency on external files is worst then dependency on online services

- cleanup and polish the report code
    - avoid using custom classes until it is neccasary, use bootstrap classes as much as possible
    - avoid inline styles in elements
    - add page title
    - remove empty styles, elements
    - refactor js code into smaller functions, so they purpose will be obvious

@mbocek WDYT?

**Comment by t0mz06** [comment]
ok sounds good will do that

**Comment by mbocek** [comment]
Instead of using jquery we can use pure ES6. 
ES6 should have enough robust and clever API for DOM manipulation.

ES6 we can use because it is dev tool and audiance - developers use quite fresh versions of browsers.

**Comment by mbocek** [comment]
For now, the report is OK. we can close #3.
